### ISSUE TITLE
Add Contributors List

### ISSUE THREAD

**Issue by yashksaini-coder** [SamarthTech/web-projects-2024#86]
@SamarthTech Your README documentation does not have a Contributors list. I would like to integrate an action workflow that would allow to add & show all the contributors in the footer section of your README.

Assign this issue to me & add **hacktoberfest** labels to me.

**Comment by darkhorse404** [comment]
We appreciate your interest but we already have a [Leaderboard website](https://open-odyssey-leaderboard.vercel.app/) live with all Contributors ranked.

**Comment by yashksaini-coder** [comment]
> We appreciate your interest but we already have a [Leaderboard website](https://open-odyssey-leaderboard.vercel.app/) live with all Contributors ranked.

okh closing this issue
